---
- name: Tomcat deployment playbook
  hosts: dev
  become: True               # If to escalate privilege
  become_method: sudo       # Set become method
  remote_user: daniel         # Update username for remote server
  roles:
    - ansible.tomcat8
